project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu:
          - text: Hands-on Exercise 1
            href: Hands-on_Ex01/Hands-on_Ex01.html
          - text: Hands-on Exercise 2
            href: Hands-on_Ex02/Hands-on_Ex02.html
      - text: In-class Exercises
        menu:
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html

    right:
      - href: index.html
        text: Home
      - about.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

