project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu:
          - text: Hands-on Exercise 1
            href: Hands-on_Ex01/Hands-on_Ex01.html
          - text: Hands-on Exercise 2 parts 1 & 2
            href: Hands-on_Ex02/Hands-on_Ex02.html
          - text: Hands-on Exercise 2 parts 3
            href: Hands-on_Ex02/Hands-on_Ex02_Local.html
          - text: Hands-on Exercise 3
            href: Hands-on_Ex03/Hands-on_Ex03.html
          - text: Hands-on Exercise 4
            href: Hands-on_Ex04/Hands-on_Ex04.html
      - text: In-class Exercises
        menu:
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
          - text: In-class Exercise 2 Spatial Weights
            href: In-class_Ex/In-class_Ex1/In-class_Ex2_Spatial.html
          - text: In-class Exercise 2 GLSA
            href: In-class_Ex/In-class_Ex1/In-class_Ex2_GLSA.html
          - text: In-class Exercise 2 EHSA
            href: In-class_Ex/In-class_Ex1/In-class_Ex2_EHSA.html
      - text: Take-home Exercises
        menu:
          - text: Take-home Exercise 1
            href: Take-home_Ex01/take_home_ex_01.html

    right:
      - href: index.html
        text: Home
      - about.html

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

